version: 2
updates:
  # Enable version updates for Git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Enable version updates for npm dependencies in theme
  - package-ecosystem: "npm"
    directory: "/themes/kodama-theme"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group related updates together
    groups:
      tailwind:
        patterns:
          - "@tailwindcss/*"
          - "tailwindcss"